version: '3.8'

services:
  xhsqrcode:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/app/dist
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/qrcode"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
